### ISSUE TITLE
Unable to auth to cluster

### ISSUE THREAD

**Issue by mdf-ido** [mbach04/nutanix_vm_provisioner#6]
Hi, thanks for creating this role ! I am currently testing and had a question. In the playbook you have in the example you list localhost, when I try on mine I can see:

TASK [nutanix_provisioner : Auth to the cluster] ********************************************************************************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: 

So I changed the localhost to an inventory list that has my NTNX cluster IP but failed to auth. 

- Are there any configs to be done on the NTNX side like adding ssh keys?
- Are you running the roles inside the NTNX server?

Thanks!

**Comment by twling** [comment]
In the example, we use localhost as the host that is executing the automation. This probably should not be any of the IPs for your nutanix cluster and the easiest way to execute this role is from the local machine where you pulled this role into from git. 

What the task above is doing, is reaching out from whatever 'localhost' is, to the URL "{{ api_url_v3 }}/clusters/list" in order to establish credentials for other API calls later on. See tasks/get_session_cookie.yml, lines 4-22. If you are getting an authentication error on that step, it may be a number of causes:

One or more of: api_url_v3, prism_user,prism_password are undefined
The prism username/password is incorrect
The prism username/password used does not have authorization for that API endpoint
Whatever the localhost machine is cannot access the API endpoint (possible networking issue).

Based on the error you posted above, I would guess that it is 'api_url_v3" that is undefined, which would make the URL for that task "/clusters/list", tricking ansible into thinking you are referring to a location on the filesystem.


To directly answer your questions: No ssh keys needed as the authentication here is using the prism username/password for the nutanix API and the role is not run from inside the NTNX server.

**Comment by mdf-ido** [comment]
Thanks for the explanation, we were able to login.
